export const API_ENDPOINTS = {
  LOGIN: "http://portal.day2daywholesale.com/api/login",
  REGISTER: "http://portal.day2daywholesale.com/api/register",
  LOGOUT: "/logout",
  FORGET_PASSWORD: "/forget-password",
  MENU: "http://portal.day2daywholesale.com/api/demowebnav",
  SUB_NAV: "http://portal.day2daywholesale.com/api/subnav",
  CATEGORIES: "http://portal.day2daywholesale.com/api/categories",
  FEATURED_CATEGORIES: "http://localhost:3000/api/featured_categories.json",
  COLLECTIONS: "http://localhost:3000/api/collections.json",
  BRANDS: "http://portal.day2daywholesale.com/api/topbrands",
  PRODUCTS: "http://localhost:3000/api/products.json",
  FEATURED_PRODUCTS: "http://portal.day2daywholesale.com/api/featuredproducts",
  TOP_SELLER_PRODUCTS: "http://localhost:3000/api/products_top_seller.json",
  ON_SELLING_PRODUCTS: "http://localhost:3000/api/products_on_selling.json",
  PRODUCT: "http://localhost:3000/api/product.json",
  PRO: "http://portal.day2daywholesale.com/api/product/",
  SINGLE_PRODUCT: "http://portal.day2daywholesale.com/api/productdetails",
  RELATED_PRODUCTS: "http://portal.day2daywholesale.com/api/productdetails",
  BEST_SELLER_PRODUCTS: "http://localhost:3000/api/products_best_seller.json",
  NEW_ARRIVAL_PRODUCTS: "http://portal.day2daywholesale.com/api/newarrival",
  FLASH_SALE_PRODUCTS: "http://portal.day2daywholesale.com/api/flashsale",
  SHOPS: "http://localhost:3000/api/shops.json",
  SHOP: "http://localhost:3000/api/shop.json",
  SEARCH: "http://localhost:3000/api/search.json",
  ORDERS: "http://localhost:3000/api//orders.json",
  ORDER: "http://localhost:3000/api//order.json",
  BANNER: "http://portal.day2daywholesale.com/api/slider/type=1",
  NEXT_PUBLIC_REST_ENDPOINT: "http://portal.day2daywholesale.com",
  ACCOUNT_DETAILS: "http://portal.day2daywholesale.com/api/me",
  PRODUCT_THUMBNAIL:
    "http://portal.day2daywholesale.com/public/assets/img/products/thumb",
  ORDER_DETAILS: "http://portal.day2daywholesale.com/api/orderlist",
  SINGLE_ORDER_DETAILS: "http://portal.day2daywholesale.com/api/orderdetails",
};
